### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by scote**
✔️  Ready to merge
- [x] Add missing templates: Bug Report + Feature Request
- [x] See if we need to remove [.github/ISSUE_TEMPLATE.md](https://github.com/sherweb/ng2-materialize/blob/master/.github/ISSUE_TEMPLATE.md)

### CODE REVIEW

**Comment by jfcere** [comment]
Where did you copied that from?
Why not just modify `CONTRIBUTING.md`?

**Comment by scote** [comment]
It seams like they change the way to use template file.

**Comment by jfcere** [comment]
So I guess this means we need to delete [.github/ISSUE_TEMPLATE.md](https://github.com/sherweb/ng2-materialize/blob/master/.github/ISSUE_TEMPLATE.md] ...

**Comment by scote** [comment]
I remove the old file.

**Pull request closed without merging**
